# Generated by Django 3.2.4 on 2021-11-25 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='9506693774', max_length=15)),
                ('name', models.CharField(default='Raj Pandey', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('insta', models.CharField(blank=True, max_length=50)),
                ('github', models.CharField(blank=True, max_length=50)),
                ('insta_username', models.CharField(blank=True, max_length=20)),
                ('facebook', models.CharField(blank=True, max_length=150)),
                ('whatsapp', models.CharField(blank=True, max_length=150)),
                ('telegram', models.CharField(blank=True, max_length=150)),
                ('cv', models.FileField(upload_to='Resume/')),
            ],
            options={
                'verbose_name_plural': 'About Me',
            },
        ),
        migrations.CreateModel(
            name='Quiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('msg', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(1, 'Resolved'), (0, 'Pending')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Graphic Designer', max_length=40)),
                ('text', models.CharField(default='There are many variations of passagesn of but the majority have suffered alteration in some form.', max_length=100)),
                ('icon', models.ImageField(upload_to='Service')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='Web Development', max_length=20)),
                ('link', models.CharField(blank=True, default='#', max_length=200)),
                ('image', models.FileField(upload_to='work')),
            ],
        ),
    ]
